### ISSUE TITLE
Reproducible subsetting flow causes a visible back end 500 error

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#21] opened 2021-04-15 15:49 UTC
To reproduce

- https://feature.clinepidb.org/ce.feature/app/eda/DS_841a9f5259
- Browse and subset
- Filter on Household->Country->Bangladesh
- Now go to Household observation type->Household water->Drinking water treatment->Chlorine test result

I'll post this on the #eda-data Slack channel

**Comment by d-callan** [comment] 2021-05-06 17:49
if i filter on chlorine test result, asking for all values, and then view country i can see there arent any results for bangaldesh. Probably we should talk about how to handle this.

**Comment by d-callan** [comment] 2021-05-06 17:50
a suggestion from Ryan: "Would be nice to throw a 400 back to the client with "Your request resulted in an empty data set.  Unable to produce visualization data" or similar."

**Comment by dmfalke** [comment] 2021-05-06 18:03
What I would *expect* is to get 0 for all values in **Chlorine test
result**.

**Comment by dmfalke** [comment] 2021-05-06 18:09
This is what we see in the prod site 
![image](https://user-images.githubusercontent.com/365139/117345501-9be75300-ae74-11eb-9123-6e8dc6e9f68d.png)

**Comment by d-callan** [comment] 2021-05-06 18:16
yea. you could do that by just using the request for the whole data set i imagine? it would probably be easy-ish to do for bar plots once i know i can get all possible unique values for a given string var as part of its metadata. histograms wont be easy though, and idk what if anything i can do about it. i cant produce a bin width for no data, and knowing the range wont be enough. wed have to have probably number of values and skewness calculated at data load time and available as metadata too i guess. i could find those values, and with it the bin width, based on the whole data set rather than the empty subset, but at that point i feel were back to my initial point, which is we may as well ignore the second request for the subset.

**Comment by dmfalke** [comment] 2021-05-06 18:18
It also just occurred to me we can use the "background" request, and infer `0`s if we get a 400 for the "foreground" request.

This also impacts visualizations. If I make a subset that only include Bangladesh, and then create a barplot viz for **Chlorine test result**, should I get a message that there is not data for this var, or should I see a plot with tickmarks for the values, but no bars? Seems like the former, given the challenges w/ histograms, if we want to be consistent.

**Comment by d-callan** [comment] 2021-05-06 18:28
agree.

**Comment by d-callan** [comment] 2021-05-26 17:32
talked w ryan. think he means to catch this before it ever gets to a viz plugin. though we did talk about plugins possibly overriding this behavior if needed at some point in the future.

**Comment by ryanrdoherty** [comment] 2021-06-22 17:44
I have a fix for this somewhere; may be on the units/scale branch however.  Will check it out and find the commit for review.

**Comment by ryanrdoherty** [comment] 2021-07-22 06:50
I have added the check for empty data streams; we will return a 204 with an appropriate message.  Dave says he will tweak the client to never ask for visualizations when the subset is empty, so this should never happen, but we are now returning a recognizable custom response (which Dave will also handle) instead of 500.

**Closed by ryanrdoherty** 2021-07-22 06:50 UTC

**Comment by bobular** [comment] 2021-07-22 09:58
> Dave says he will tweak the client to never ask for visualizations when the subset is empty, so this should never happen, but we are now returning a recognizable custom response (which Dave will also handle) instead of 500.

Isn't the problem that we don't know if the visualization request will return an empty result until we make it?

The subset can be non-empty, but the combination of (for example) X and Y variable choices might lead to an empty result.

**Comment by dmfalke** [comment] 2021-07-22 10:52
The issue is when the subset is empty and R gets an empty result from the
merging service (or something like that). I verified that with Ryan.

**Comment by bobular** [comment] 2021-09-29 14:45
Seems like there might not be any 500 errors at the moment.
The subsetting example in the issue description works OK.  (but will need to check with a numeric variable too)

In viz - there are no errors
![image](https://user-images.githubusercontent.com/308639/135291229-58c7d6a3-b6ab-46de-89dc-aea4819eb8c4.png)

But some work on empty plots would be useful - as raised in this untriaged ticket
https://github.com/VEuPathDB/EdaNewIssues/issues/151
