### ISSUE TITLE
500 error happens in Amazonia_brazil_cohort study when use certain vars to facet

### ISSUE THREAD

**Issue by aaronwlsong** [VEuPathDB/EdaDataService#146] opened 2021-11-23 22:23 UTC
As the title says, when x=" Observation date",  y=" ITN last night",  facet=" Malaria since last observation date, from medical record", or " Plasmodium species causing malaria since last observation, from medical record", the 500 error happens. 

![image](https://user-images.githubusercontent.com/61077845/143138260-22c387cb-66a3-46ef-af19-26b5dc425024.png)

![image](https://user-images.githubusercontent.com/61077845/143138563-49447fa6-9e8e-42e4-b8c1-aa77d1dc19a4.png)

**Comment by d-callan** [comment] 2022-02-07 18:44
this is a duplicate of veupathdb/plot.data#101. given that issue has been referenced now in a couple different cases, it might be becoming a higher priority.

**Comment by d-callan** [comment] 2022-02-07 18:46
also see veupathdb/edadataservice#118. i think we have a open question whether wed like a 400 or valid empty response when theres no plottable data.

**Comment by danicahelb** [comment] 2022-02-09 03:55
closing this as it is a duplicate of https://github.com/VEuPathDB/plot.data/issues/101. Thanks @d-callan

**Closed** 2022-02-09 03:56 UTC
Labels: bug

**Comment by danicahelb** [comment] 2022-02-09 03:57
@aaronwlsong this ticket needs to wait until https://github.com/VEuPathDB/plot.data/issues/101 is complete to be QA'd so I've added a paused label

**Comment by nkittur-uga** [comment] 2022-02-28 18:02
I got an informative note about why the plot is blank: "Expected one or more data series, but got zero" so this issue is resolved.
