### ISSUE TITLE
500 error when trying to plot variables with no data

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EdaDataService#145] opened 2021-12-21 19:53 UTC
EX: GEMS1 Case-control
1) subset so 'Case or control participant' = Yes
2) create a histogram where Main = "Diarrheal episode duration"
see the following error message and an empty plot

<img width="1031" alt="Screen Shot 2021-12-21 at 1 51 17 PM" src="https://user-images.githubusercontent.com/54597319/146989264-2d8a548a-c891-4150-8028-4dda4bd30153.png">

Possible solutions: 
1) Instead of showing a 500 error, add text explaining that the chosen variable has no data given the current subset. 
2) Grey out variables with no data remaining given the subset and add a new tool tip for this specific reason variables aren't available (this sounds harder to me, but I'm obviously not best placed to judge)

**Comment by d-callan** [comment] 2022-02-07 18:04
so if i filter gems1 by case = yes, i can see there is data for diarrheal duration. so im not sure its a problem to do w no data remaining. also, i cant currently recreate this on the qa site. whatever the problem was, it seems to be resolved. you can obviously reopen if you disagree.

**Comment by SheenaTomko** [comment] 2022-02-07 19:59
Reopening. Realized that my description above was incorrect. You have to subset so "Case or control participant" = "Control", then try to create a histogram where Main = "Diarrheal episode duration". The 500 error still appears.

**Comment by d-callan** [comment] 2022-02-07 20:15
ok. i see it now, and can confirm this as another duplicate of veupathdb/plot.data#101

**Comment by danicahelb** [comment] 2022-02-09 03:59
closing this as it is a duplicate of https://github.com/VEuPathDB/plot.data/issues/101. Thanks @d-callan

adding a paused label so that we wait to QA until after a fix is checked in for the issue above

**Closed by danicahelb** 2022-02-09 03:59 UTC
Labels: bug, medium cost

**Comment by nkittur-uga** [comment] 2022-02-28 17:30
Banner text is now helpful: "The visualization cannot be made because there is no plottable data for currently selected variable(s) in the current subset." QA is complete.
