### ISSUE TITLE
RxC Contingency Table errs while plotting 'floor material' by 'country' for prism

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/EdaDataService#68] opened 2021-08-09 16:56 UTC
danielle says this is fixed.  adding this issue in EdaDataService so it can be tested

**Comment by aaronwlsong** [comment] 2021-08-19 17:53
**QA checking**
_1. Using the same variables for x-axis and y-axis in PRISM study_
On QA website, the issue still exists, cannot generate the figure.
<img width="1660" alt="WeChatede34ea723ec77f2a06148b3ebd0bc79" src="https://user-images.githubusercontent.com/61077845/130118042-8d754347-b06d-4909-bbbc-d3563497ca06.png">

_2. Using the different variables for x-axis and same variable for y-axis in PRISM study_
On QA website,the issue still exists, cannot generate the figure. This issue happens for all available variables under category "Household". 

<img width="1590" alt="WeChat6e7b544212931eb5c87448f060c4dfff" src="https://user-images.githubusercontent.com/61077845/130118931-3c1e985d-df43-4430-8118-a04f3469ba1a.png">

_3. Using the different variables for x-axis and different variable for y-axis in PRISM study_
It works for other variables, only when variable="country", the figure cannot be produced. 
<img width="1580" alt="WeChatb074cf2431b0aceb857d13c54c8e14c9" src="https://user-images.githubusercontent.com/61077845/130119277-62c5afb2-f89a-4e23-9109-969008b74da4.png">

<img width="1590" alt="WeChat62e71b8f8218f826854ebffd8ca9fe4b" src="https://user-images.githubusercontent.com/61077845/130119473-6d32fc06-ad53-42fd-89fd-5224a40eaf83.png">

**Comment by danicahelb** [comment] 2021-08-20 20:41
@d-callan assigning back to you, issues haven't been addressed

**Comment by d-callan** [comment] 2021-08-24 03:32
i cant reproduce this locally. i know there are some failed builds recently for backend services. maybe thats related, not yet sure.

**Comment by d-callan** [comment] 2021-08-25 02:08
should be working on the qa site now after some technical hiccups w deployment. re-closing.

**Comment by SheenaTomko** [comment] 2021-08-25 14:02
Can do X-axis = Floor material and Y-axis = Country now, however, if you try and flip them there's an error message (presumably because Country only has one value). Should this be a new ticket?

<img width="1211" alt="Screen Shot 2021-08-25 at 9 02 21 AM" src="https://user-images.githubusercontent.com/54597319/130805002-43dfbda9-b4d1-434a-b477-81f413c54aff.png">

**Comment by d-callan** [comment] 2021-08-25 14:36
i think this can be closed. there is already an existing issue in veupathdb/plot.data#79 for the error @SheenaTomko mentioned

**Comment by SheenaTomko** [comment] 2021-08-25 14:38
Thanks @d-callan. I'll close this

**Closed by SheenaTomko** 2021-08-25 14:38 UTC
Labels: bug
