### ISSUE TITLE
Histogram request for date variable with filters gives 500

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#33] opened 2021-05-13 20:53 UTC
Filter is on Household->Floor material using popular choices (so retains 87% of households)

outputEntity/Variable is Participant->Demographics->Birth date, which is available for 100% of participants.

So I don't think it's a problem with zero results.

(It works with no filter, and also fails with a filter on the same entity.)

Service: https://dfalke-b.clinepidb.org/eda-data
Endpoint: /apps/pass/visualizations/histogram
POST body:
```
{
	"config": {
		"binSpec": {
			"type": "binWidth",
			"units": "month",
			"value": 1
		},
		"outputEntityId": "EUPATH_0000096",
		"valueSpec": "count",
		"viewport": {
			"xMax": "2011-02-02",
			"xMin": "2007-12-11"
		},
		"xAxisVariable": {
			"entityId": "EUPATH_0000096",
			"variableId": "EUPATH_0000150"
		}
	},
	"filters": [
		{
			"entityId": "PCO_0000024",
			"stringSet": [
				"Finished floor; cement",
				"Natural floor; earth/sand"
			],
			"type": "stringSet",
			"variableId": "EUPATH_0000006"
		}
	],
	"studyId": "GEMSCC0002-1"
}
```

**Comment by d-callan** [comment] 2021-05-19 14:04
Duplicate of #28

**Closed** 2021-05-19 14:51 UTC
Labels: bug
