### ISSUE TITLE
Visualizations: GEMS1 bug when selecting y-axis variable before x-axis variable for scatter plot

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaDataService#94] opened 2021-09-14 20:33 UTC
In the scatter plot for GEMS1, if i select "Weight" (under Participant repeated measure) for my x-axis, I am only able to select other variables under Participant repeated measure for my y-axis. All terms under Sample are greyed out, for example.

However, If i select a Sample variable for my y-axis BEFORE selecting my x-axis variable, I am then able to select a variable under Participant repeated measure for my x-axis. Once i've selected my variables in this order i get an error message.

![image](https://user-images.githubusercontent.com/25450900/133329612-9502c5bc-ee52-48d4-bbd2-2f4c1e223126.png)

**Comment by moontrip** [comment] 2021-09-20 16:11
@danicahelb Please check this behavior again as I cannot reproduce this issue: tested at https://qa.clinepidb.org/. There might have been changes at either frontend or backend like addressed at other issue since your initial tests.

**Comment by SheenaTomko** [comment] 2021-09-24 20:08
This is no longer an issue. If you select the Y-axis Aeromonas variable, then all participant repeated measure variables are inaccessible on the X-axis, since it is on a different branch. Closing and marking as complete

**Closed by SheenaTomko** 2021-09-24 20:08 UTC
Labels: bug, low cost
